### ISSUE TITLE
I do not have these fields vmw_vc_*

### ISSUE THREAD

**Issue by kossatov1989** [s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI#2]
Good afternoon, I have done everything according to the instructions. I am getting logs from Vcentr, but the dashboards are not working. I get this error - Unknown field: Request contains unknown field: vmw_vc_Event.
I do not have these fields vmw_vc_*

**Comment by kossatov1989** [comment]
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/89f7d66d-6021-4947-b3b4-b978c2db13f5)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/6875e729-97b9-465c-8cc3-ea5fa098f6a3)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/41355fde-8df9-4b1a-b750-6fc7794c162d)

**Comment by s0p4L1n3** [comment]
Could you tell me what version of Graylog / Opensearch you are using ?

**Comment by s0p4L1n3** [comment]
Ok so I just test on a new Graylog server, no error on my side.

<img width="357" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/9677b57c-e583-4fc1-8d63-3aaa5e1faecc">

Can you check if you have this on your Graylog pipeline side > manage rule side

<img width="942" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/1d4b51e5-bfb9-4200-bffc-ae19fa47d90f">

If yes then can you filter in your stream if you have Event data, If yes, deploy one of the messages, left click on the field `message` > Create extractor > Grok Pattern  (just to test if you can extract data)

<img width="596" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/60938d5f-607a-42a3-8a69-b09d5aad2c3e">

On the extractor copy paste this grok pattern (grok pattern that extract the fields that is missing on your side)
_note: on pipeline rule, as it is java language, you need to add double `\\` if your grok pattern in extractors has simple `\`_ 

```
%{DATA:vmw_vc_Event} \[%{BASE10NUM:vmw_vc_eventId}\] \[%{DATA:vmw_vc_partInfo}\] \[%{TIMESTAMP_ISO8601:vmw_vc_createdTime}\] \[vim.event.%{DATA:vmw_vc_eventType}\] \[%{DATA:vmw_vc_severity}\] \[%{DATA:vmw_vc_user}\] \[%{DATA:vmw_vc_target}\] \[%{DATA:vmw_vc_chainId}\] \[%{DATA:vmw_vc_desc}\]
```

Click try against example and it should show the fields extracted

<img width="639" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/d4557f1b-ce2d-493c-b60b-0e233a292784">


If it does not work, it can means multiple things but let's confirm just this now and tell me the result.

**Comment by kossatov1989** [comment]
Hello
1
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/ceb44fc9-cfb7-4d44-ba36-a02697b87cc3)
2
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/478b6e23-c6f1-4e7a-9ddb-610a78403784)
3
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/1e299f4b-aec2-4aeb-9cd4-2aa03cc7acfd)
4
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/b30e6d28-d920-47cc-b631-30e2f78a9071)

I don't have a Grok pattern (DATA), can you provide one?

**Comment by kossatov1989** [comment]
i add Grok pattern DATA
1
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/12cd12ed-a36d-4c6c-92d2-cca715849757)

2 add \\
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/ca9c3c75-5760-4033-8f55-5f67c822ae5b)

**Comment by kossatov1989** [comment]
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/784957bf-a6c5-43d0-bf36-42fce3efdcc9)

**Comment by kossatov1989** [comment]
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/4b7b9b67-5483-4b80-bda8-1b9f921b463d)

**Comment by kossatov1989** [comment]
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/f6358fd2-ba36-4c50-aed8-603e3d835820)

![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/547195b6-143b-43ce-954f-6e115001bcdc)

**Comment by s0p4L1n3** [comment]
How come you do not have DATA grok pattern as it is built in grok pattern provided by Graylog ? I only used the provided one.

The issue is that your field `message` start with `message: Event` while on my VCSA, it start with `Event` without the prefix `message:`
It's weird 

<img width="894" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/8ada54a3-13d5-4779-8791-08fdb9ddb76a">

For your pipeline named: `Syslog - VMWARE st12vcenter01`, edit it and:

- try replace `%{DATA:vmw_vc_Event} \\[%{BASE10NUM:vmw_vc_eventId}\\] \\[%{DATA:vmw_vc_partInfo}\\] \\[%{TIMESTAMP_ISO8601:vmw_vc_createdTime}\\] \\[vim.event.%{DATA:vmw_vc_eventType}\\] \\[%{DATA:vmw_vc_severity}\\] \\[%{DATA:vmw_vc_user}\\] \\[%{DATA:vmw_vc_target}\\] \\[%{DATA:vmw_vc_chainId}\\] \\[%{DATA:vmw_vc_desc}\\]`

- with this `message: %{DATA:vmw_vc_Event} \\[%{BASE10NUM:vmw_vc_eventId}\\] \\[%{DATA:vmw_vc_partInfo}\\] \\[%{TIMESTAMP_ISO8601:vmw_vc_createdTime}\\] \\[vim.event.%{DATA:vmw_vc_eventType}\\] \\[%{DATA:vmw_vc_severity}\\] \\[%{DATA:vmw_vc_user}\\] \\[%{DATA:vmw_vc_target}\\] \\[%{DATA:vmw_vc_chainId}\\] \\[%{DATA:vmw_vc_desc}\\]`


The VMWARE docs describe the normal log format... try debugging why it append `message:` before your message`(maybe syslog particularity ?)
https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-monitoring-performance/GUID-F92A08A1-646A-4DCD-8DB0-47E6D2B49C5D.html

**Comment by kossatov1989** [comment]
I apologize, I didn't put the message in correctly.
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/6f36e282-3dd6-4aab-9117-acfd8b74769f)

**Comment by kossatov1989** [comment]
If I use \\\ I get an error.
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/f96676d3-91a1-44d3-8a44-ad3f386efd3e)
if \\
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/7c0069b1-789c-4c86-b022-2f48dfa8752a)

**Comment by kossatov1989** [comment]
Now the problem is that Syslog - VMWARE s1t2vcenter01 does not receive messages

![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/e4c65cca-eceb-404e-8462-f299bacbfa06)

**Comment by s0p4L1n3** [comment]
> If I use \\ I get an error. ![image](https://private-user-images.githubusercontent.com/130131477/305052720-f96676d3-91a1-44d3-8a44-ad3f386efd3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTYxNTIsIm5iZiI6MTcwNzk5NTg1MiwicGF0aCI6Ii8xMzAxMzE0NzcvMzA1MDUyNzIwLWY5NjY3NmQzLTkxYTEtNDRkMy04YTQ0LWFkM2YzODZlZmQzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTE3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTAyOTFhNTljNGZlMDE3OTNkYjA2MTdiODc4MGE0ODUxNjUwOTEyOGM2ZjQ5ODE5ODJiNTNmYzNmMTkxZTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qqw5qx9x6xQr7vLuSVt910GXxeLvIBCVMgtQN1NXMKo) if \ ![image](https://private-user-images.githubusercontent.com/130131477/305053025-7c0069b1-789c-4c86-b022-2f48dfa8752a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTYxNTIsIm5iZiI6MTcwNzk5NTg1MiwicGF0aCI6Ii8xMzAxMzE0NzcvMzA1MDUzMDI1LTdjMDA2OWIxLTc4OWMtNGM4Ni1iMDIyLTJmNDhkZmE4NzUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTE3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDg0MGVlYzY1ZDAxMGQ4ZTU1MjY5ZmQ0NGY0NTA0MzNmM2JiMTg1M2ZiMjM3ZTVlYjE5NDQ0ZDgzNmVmOTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q5MCba0oYggo36tyoMWtuaJf68mDk1Mx0JBo9HIjGE4)

Yes it is normal, Pipeline rules uses Java language so you need to double \\ but for Extractors you need one \ as it does not use java.

**Comment by s0p4L1n3** [comment]
> Now the problem is that Syslog - VMWARE s1t2vcenter01 does not receive messages
> 
> ![image](https://private-user-images.githubusercontent.com/130131477/305053351-e4c65cca-eceb-404e-8462-f299bacbfa06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTYyMjgsIm5iZiI6MTcwNzk5NTkyOCwicGF0aCI6Ii8xMzAxMzE0NzcvMzA1MDUzMzUxLWU0YzY1Y2NhLWVjZWItNDA0ZS04NDYyLWYyOTliYWNiZmEwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMTE4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmQ5YmEwOGYwYWFlMTdjYjJlYjNlNDgxOTk1MzdhNDg4YWJlZDExZTQyMGUyOGYyODVhNmQ1MGNiNjc5OGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bMFNCNDG6Q2gh1gpWNES7F_RuLP_CRtMoo0e74k9DA4)

It does not receive logs specific to the pipeline rules yes, but it does receive logs on the global stream. 
So it is not that it does not work, you just need to triggers these event to receives some logs.

If you want to check if this pipeline rule is effective, do these action:

- log in/log out from vsphere 
- do action on your virtual machine (snapshot, stop start)

below, i reverted some snapshot etc:

<img width="1819" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/03c61e6a-a5dd-4aef-ada2-9ed67f1be8ac">

**Comment by kossatov1989** [comment]
Hello,

As you can see logs suitable for parsing are available
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/2c869750-b3df-4a6c-a6a8-1fcb73ddd109)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/56266c35-8c7e-4841-80d8-21cb5684c7b9)

but the dashboard is still empty.
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/e59df283-67b1-4cc1-8172-f09002c466c4)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/08d36c41-690b-4027-9bb7-0d7df5599515)

because Pirelins doesn't parse logs. 
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/ef47dd60-a736-40d8-ad54-37ad4c2760fb)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/a3734fd5-3488-4d45-b7cd-ab56df88c299)

**Comment by kossatov1989** [comment]
I did a simulation
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/dcc67020-7f2f-4f14-ad05-3a1673a98417)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/be8c62ab-cc30-41e3-bd71-03aec7870e31)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/bdd26ee4-74ad-4516-9bf6-b8457acfd512)
it's okay


but incoming messages in Streams (VCSA), Pipelines are not processed((((
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/5ac9dcbc-ecc3-4220-a308-a183ad87458b)

**Comment by kossatov1989** [comment]
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/ca601237-bb32-4e46-93f5-103389de6288)

Strange, but when I select All messages, Pipeline starts working even though VCSA is running messages

![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/ee216684-8116-40b5-9e7a-f1b2444ef627)

**Comment by s0p4L1n3** [comment]
Check your VCSA stream rules because if the pipeline works when you select all message stream as source, it means the VCSA logs does not go throught the correct stream.

My VCSA stream rules is this one, and yours should be s1t2vcenter01
`source must match exactly vcsa`

Could you try again a pipeline simulation and instead of pasting Full message in RAW field, paste message field.

If the simulation give you the parsed result, then it should work and it means there is an error somewhere else.

Check also your message processing order, it should read the stream first then the pipeline.
<img width="1617" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/80aac732-ac58-438a-9e91-419538763026">

**Comment by kossatov1989** [comment]
Good morning. 
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/31068f8b-a86f-404c-9d71-16f3529bad70)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/aaf9f8e4-b733-487f-b82b-f922f49decb4)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/5ba731e6-1df8-4c35-a393-809dd1fc00b8)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/eff5ffb1-9487-46e9-ae9b-ca93fab7f9ac)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/00d8a6d4-c028-4aac-9ddc-ccbc6fc0f8fe)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/c777956a-ac94-43b5-8c5c-8f63341d48e9)

I can see that the thread rules are working and messages are put into it, but they are not processed by Pipelines. 
full_message - parses the message 
message - error output

**Comment by s0p4L1n3** [comment]
On your last image, you can see that the pipeline are processed before the Stream message.

You should setup this way:

1 | Message Filter Chain
2 | Stream Rule Processor
3 | Pipeline Processor

First thing, why do you have VCSA logs on your `All message stream` (is it your default stream ?), on my vcsa stream setting I ensure to have logs only on this stream and not on the default one.
<img width="395" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/589ad0e7-ad12-4c7a-bc42-f0dfa7f5b16d">

Then, you should know that you are trying to simulate the parsing with the field `Full message` while I did not write any parser for this field.
You should focuses on `message` field only.

- When I simulate, I choose VCSA Stream:

<img width="1105" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/48aff40c-96f0-4096-97cd-3f0d1ee74fc7">

- The result are here and are working
- 
<img width="1879" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/d120f52a-2595-4286-b6af-6c6a1404fc18">

BUT FOR YOU, remember that you modified one of you pipeline rules because you had `message: Event[xxxxx]` instead of `Event[]` but now you do not see it because it already parse.

BUT if you try to simulate again and if you simulate by pasting the RAW Message (that is already parsed), the pipeline rules will not parse it because it is looking for message field starting by `message: Event`


You should try change the message processing. 
Clean the fact that you have VCSA logs in your All message stream because it seems to confuse you
Try again to simulate and check the details/debug mode:

<img width="964" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/1ed81b10-9f9e-4e1e-a1d8-3046b4976ee9">


It's difficult to me to help you further, but I will try to edit my content pack because as I named some variable vcsa1 or vcsa2 or event pipeline rules name containing VCSA, with my requirements saying replace VCSA by your vcsa server name, it can have conflict somewhere, but I'm not sure because I got some people that told me it was working fine.

**Comment by kossatov1989** [comment]
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/e7d626bb-b606-4f38-a963-5ec200fb8c5e)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/b7328a1b-8ea2-4fdb-a38d-a4060608bb59)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/a22fed42-c28c-494d-be78-f14213b64526)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/e7149a92-5e91-4673-8eca-582f8f160899)

![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/61b33610-27c7-4c3c-9112-6ed26caf8a5e)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/ae672d50-a9c6-4af5-9597-baf914e5586f)

![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/abc59a81-b04b-49db-8407-652808d99c9d)
![image](https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/130131477/ab1619ec-10f9-48ad-860e-23ee7be357f6)

I don't understand why parsing from Streams VCSA doesn't work for me.

**Comment by s0p4L1n3** [comment]
What is your All message streams ? Can you check what is the condition of the stream for message to be forwarded in ?

Did you applied this settings for the message processing order ?
<img width="1556" alt="image" src="https://github.com/s0p4L1n3/Graylog_Content_Pack_VMWare-8.X-forVCSA-ESXI/assets/126569468/ce6b8279-fa0c-4a9d-983d-f264d2f66ea9">

Can you check your syslog input if it is the right one ? Because in my template, the syslog is called Syslog (vcsa) and yours is the default syslog tcp.

It look like to me that syslog TCP input is going to All message stream. but is syslog tcp is related to VCSA syslog ?

**Comment by kossatov1989** [comment]
Good afternoon, I have not solved this problem, but the logs went and I can see them, I think we can close this issue, I do not have time to deal with it further. Thank you for your help.

**Comment by s0p4L1n3** [comment]
Alright, feel free to open a new issue, I will be glad to help you at my best !
